version: "3.8"

services:
  server:
    container_name: sea-of-thieves-clone
    image: node:16.17.0-alpine
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8081:80
    networks:
      - docker_custom_network


networks:
  docker_custom_network:
    external: true
